config:
  backup: true
  banner: true
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  link_dotfile_default: link_children
  link_import_default: link_children
  link_on_import: link_children
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop

dotfiles:
  less:
    dst: ~/.less
    src: less/.lesskey
    trans: lesskey
    link: nolink
  urxvt:
    dst: ~/
    src: urxvt/
  sxhkd:
    dst: ~/
    src: sxhkd/
  rofi:
    dst: ~/
    src: rofi/
  ssh:
    dst: ~/
    src: ssh
  rofi:
    dst: ~/
    src: rofi
  rofi-pass:
    dst: ~/
    src: rofi-pass
  ranger:
    dst: ~/
    src: ranger
  parcellite:
    dst: ~/
    src: parcellite
  neomutt:
    dst: ~/
    src: neomutt
  mpv:
    dst: ~/
    src: mpv
  git:
    dst: ~/
    src: git
  firefox:
    dst: ~/.mozilla/firefox/profile
    src: firefox
  emacs:
    dst: ~/
    src: emacs
  dunst:
    dst: ~/
    src: dunst
  compton:
    dst: ~/
    src: compton
  bspwm:
    dst: ~/
    src: bspwm
  zsh:
    src: zsh/
    dst: ~/

profiles:
  base:
    dotfiles:
      - emacs
      - git
      - less
      - neomutt
      - ssh
      - sxhkd
      - zsh
  x11:
    dotfiles:
      - bspwm
      - compton
      - dunst
      - firefox
      - mpv
      - parcellite
      - ranger
      - rofi
      - rofi-pass
      - urxvt
  desktop:
    dotfiles:
    include:
      - base
      - x11

trans:
  lesskey: lesskey -o {1} {0}
