config:
  backup: true
  banner: true
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  link_dotfile_default: link_children
  link_import_default: link_children
  link_on_import: link_children
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop

dotfiles:
  x11:
    src: x11/
    dst: /etc/X11
  x11_desktop:
    src: desktop/x11
    dst: /etc/X11
  portage:
    src: portage
    dst: /etc/portage
  portage_t25:
    src: t25/portage
    dst: /etc/portage
  portage_fileserver:
    src: fileserver/portage
    dst: /etc/portage
  portage_desktop:
    src: desktop/portage
    dst: /etc/portage

profiles:
  fileserver:
    dotfiles:
      - portage_server
    include:
      - base
  t25:
    dotfiles:
      - portage_t25
    include:
      - base
  desktop:
    dotfiles:
      - x11_desktop
      - portage_desktop
    include:
      - base
  base:
    dotfiles:
      - x11
      - x11_desktop
      - portage
