#! /bin/sh

sxhkd &


bspc monitor -d I II III IV

MONITOR=`xrandr --listmonitors | cut -f6 -d' ' | sed '/^$/d' | head -n 1` polybar top &

bspc config border_width 0
bspc config window_gap 40

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true

bspc rule -a Emacs state=tiled
bspc rule -a Pinentry state=floating

~/.fehbg
compton --config "$HOME/.config/compton.conf" -b

bspc config top_padding 36
