#!/bin/bash
sxhkd &

MONITORS=`xrandr --listmonitors | cut -f6 -d' ' | sed '/^$/d'`
PRIMARY_MONITOR=`echo "$MONITORS" | head -n 1`

bspc monitor $PRIMARY_MONITOR -d I II III IV

if [[ 2 -eq `echo $MONITORS | wc -l` ]]; then
    SECONDARY_MONITOR=`echo $MONITORS | tail -n 1`
    bspc monitor $SECONDARY_MONITOR -d V VI VII IX
fi

bspc config border_width 0
bspc config window_gap 20

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true

bspc rule -a Emacs state=tiled

~/.fehbg &
dunst &
parcellite -d &
compton --config "$HOME/.config/compton.conf" -b
