#! /bin/sh

sxhkd &

# lemonbar
polybar top &

bspc monitor -d I II III IV

bspc config border_width 2
bspc config window_gap 40

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true

bspc rule -a Emacs state=tiled
bspc rule -a Pinentry state=floating

~/.fehbg
compton --config "$HOME/.config/compton.conf" -b

bspc config top_padding 36
