#!/bin/zsh

RSYNC_COMMAND=/usr/bin/rsync
RSYNC_OPTS="--archive --exclude=lock --delete -L --rsh ssh -v"
PROFILE_DIR="$HOME/.mozilla/firefox/profile"
REMOTE="$SSH_USER@fileserver.hallabro:firefox/"

if [[ -z "$@" ]]; then
    echo "Usage: $0 up|down"
    exit 1
fi

if [[ "up" == "$1" ]]; then
    $RSYNC_COMMAND ${=RSYNC_OPTS} $PROFILE_DIR $REMOTE
elif [[ "down" == "$1" ]]; then
    $RSYNC_COMMAND ${=RSYNC_OPTS} $REMOTE $(dirname $PROFILE_DIR)
fi

