export ZSH=$HOME/.oh-my-zsh
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

ZSH_THEME="theunraveler"
plugins=(git)

source $ZSH/oh-my-zsh.sh
