export ZSH=$HOME/.oh-my-zsh
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

set HIST_IGNORE_SPACE

ZSH_THEME="theunraveler"
plugins=(git)

source $ZSH/oh-my-zsh.sh

eval $(keychain ~/.ssh/id_rsa B4C48F45F16E612B625004B802E221882616B4EB --agents ssh,gpg --eval --noask --quiet)
