#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#585858'

# remove all existing keybindings
hc keyunbind --all

Mod=Mod4

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt
hc keybind Mod4-p spawn dmenu_run -nf "#E8E8E8"
hc keybind Mod4-r spawn scrot -u

# focusing clients
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# moving clients
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# tags
tag_names=( "1" "2" "3" "4" )
tag_keys=( {1..4} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-r remove
hc keybind $Mod-f fullscreen toggle

# mouse
hc mouseunbind --all

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#585858'
hc set frame_bg_active_color '#B8B8B8'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 0
hc set frame_transparent_width 8
hc set frame_gap 10

hc attr theme.active.color '#B8B8B8'
hc attr theme.normal.color '#383838'
hc attr theme.urgent.color '#DC9656'
hc attr theme.inner_width 0
hc attr theme.inner_color '#282828'
hc attr theme.border_width 0
hc attr theme.floating.border_width 3
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color '#282828'
hc attr theme.active.inner_color '#282828'
hc attr theme.active.outer_color '#282828'
hc attr theme.background_color '#282828'

hc set window_gap 1
hc set frame_padding 2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 1

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'
hc detect_monitors

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

~/.config/herbstluftwm/panel.sh
